name: Process Pre-Release
run-name: Process Pre-Release

on:
  release:
    types: [ prereleased ]

env:
  TAG: ${{ github.event.release.tag_name }}

jobs:
  info:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Print Info
        run: |
          if [[ ! "$TAG" =~ ^[0-9]+\.[0-9]+\.[0-9]+-beta.[0-9]+$ ]]; then
            echo "Invalid tag $TAG"
            exit 1
          fi

          echo "Valid tag."
